services:
  - type: web
    name: customer-churn-prediction
    env: docker
    plan: free
    branch: master
    repo: https://github.com/Epsibamiriam24/Customer_churn_mlops_pipeline
    region: oregon
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 8501
    buildFilter:
      paths:
        - src/**
        - Dockerfile
        - requirements.txt
        - artifacts/**